### PR TITLE
Feature/conn

### PR DESCRIPTION
**Pull request by mohamm-alsaid**
## This PR adds the following features: 
* Connects to DER
* Disconnects from the DER
* Specification for the two features using:
  * mock of cta2045 Device class
  *  mock of cta2045 SerialPort class
----
### Screenshot of Specs:
image

### CODE REVIEW

**Review by blusky-cloud — APPROVED** [review]
This all looks awesome! Not that I'm familiar enough with this code to really know from a look-over, but yeah!

**Comment by psu-powerlab** [comment]
- Lets follow the member variable naming convention of "variable_name_" with a trailing underscore.
- Make sure your scoping is consistent. I noticed you would sometimes scope if (true) { something} and sometimes not.

Other than that it looks fantastic. I will make the merge once those two things are taken care of.

**Review by psu-powerlab — CHANGES_REQUESTED** [review]
- follow member variable naming convention
- always use scoping brackets { }

**Comment by mohamm-alsaid** [comment]
> 
> 
>     * follow member variable naming convention
> 
>     * always use scoping brackets { }

Fixed naming convention. Scoping already conforms to the [standard](https://google.github.io/styleguide/cppguide.html#Conditionals).

**Pull request merged**
